name: haraka_afya_ai
description: "AI-powered health companion app with multi-language support."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.5
  geolocator: ^10.0.0
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  flutter_dotenv: ^5.1.0

 
 

  # UI & Animation
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.2.1
  lottie: ^2.7.0  # Correct stable version for animations
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^16.0.0
  
  # Backend & APIs
  dio: ^5.3.3
  
  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.0
  
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/onboarding3.jpg
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/twitter.png
    - assets/mpesa.png
    - assets/airtel.png
    - assets/stripe.png
    - assets/paypal.png
    - .env

  