name: haraka_afya_ai
description: "AI-powered health companion app with multi-language support."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animation
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.2.1
  lottie: ^2.7.0  # Correct stable version for animations
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.0.0
  
  # Backend & APIs
  http: ^1.1.0
  dio: ^5.3.3
  
  
  
  
  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.0
  
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/onboarding3.jpg
  
  
  