// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPRcC9zfq2TTUtgrGm2W8ua90gFTnh-L8',
    appId: '1:73346163295:web:95b1324fba42078b0b71ea',
    messagingSenderId: '73346163295',
    projectId: 'haraka-afya-ai-5b3a4',
    authDomain: 'haraka-afya-ai-5b3a4.firebaseapp.com',
    storageBucket: 'haraka-afya-ai-5b3a4.firebasestorage.app',
    measurementId: 'G-4TSKZXDG2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnazPRk9MtOh4KHupfy7zA6CybEdJ7okk',
    appId: '1:73346163295:android:aca1c55f93b1273f0b71ea',
    messagingSenderId: '73346163295',
    projectId: 'haraka-afya-ai-5b3a4',
    storageBucket: 'haraka-afya-ai-5b3a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa1eUIrh2iht09961hHpeOhDd2orspvKU',
    appId: '1:73346163295:ios:84dde00ad44a81ec0b71ea',
    messagingSenderId: '73346163295',
    projectId: 'haraka-afya-ai-5b3a4',
    storageBucket: 'haraka-afya-ai-5b3a4.firebasestorage.app',
    iosBundleId: 'com.example.harakaAfyaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa1eUIrh2iht09961hHpeOhDd2orspvKU',
    appId: '1:73346163295:ios:84dde00ad44a81ec0b71ea',
    messagingSenderId: '73346163295',
    projectId: 'haraka-afya-ai-5b3a4',
    storageBucket: 'haraka-afya-ai-5b3a4.firebasestorage.app',
    iosBundleId: 'com.example.harakaAfyaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPRcC9zfq2TTUtgrGm2W8ua90gFTnh-L8',
    appId: '1:73346163295:web:8fcfc82a221fc38f0b71ea',
    messagingSenderId: '73346163295',
    projectId: 'haraka-afya-ai-5b3a4',
    authDomain: 'haraka-afya-ai-5b3a4.firebaseapp.com',
    storageBucket: 'haraka-afya-ai-5b3a4.firebasestorage.app',
    measurementId: 'G-KKL18JRKF8',
  );
}
